version: '3.8'
services:
  webapp:
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ../OT10XApp:/usr/src/app
      - /usr/src/app/node_modules  # preserve container's node_modules
    command: npm run dev
